# Use an official OpenJDK image as the base
FROM openjdk:26-slim-trixie

# Set the working directory
WORKDIR /app

# Copy the jar file into the container
COPY ./.mvn/wrapper/* /

# Expose the port your app runs on (e.g., 8080)
EXPOSE 8080

# Run the jar file
CMD ["java", "-jar", "maven-wrapper.jar"]